--
-- USO DE COUNT, LIMIT Y ORDER BY
--

-- EJERCICIO 1. CALCULAR EL NUMERO DE SPOTS DE TELEVISION ALMACENADOS EN LA BASE DE DATOS

SELECT COUNT(*)
FROM "Marketing"."TV" ;

-- Respuesta: 2824

-- EJERCICIO 2. OBTENER 15 REGISTROS DE LA TABLA SOCIAL
SELECT *
FROM "Marketing"."Social"
LIMIT 15

-- EJERCICIO 3. OBTENER EL ANUNCIO DE RADIO CON MAYOR INVERSION
SELECT *
FROM "Marketing"."Radio"
ORDER BY "Radio"."Inversión" DESC
LIMIT 1

-- Respuesta: "2019-04-01 06:44:39"	"6:00-10:00"	"CADENA SER"	"MEJORA IMAGEN DE MARCA ABRIL"	"MENCION"	"ANTEPENULTIMA"	20	1.27	1455.57

