--
-- USO DE WHERE, LIKE Y IN
--

-- EJERCICIO 1. OBTENER AQUELLOS SPOTS DE TELEVISION EMITIDOS EN ANTENA 3 CUYOS GRPS SEAN SUPERIORES A 5. ¿CUANTOS SON?
SELECT *
FROM "Marketing"."TV"
WHERE "TV"."Cadena" = 'Antena 3' AND "TV"."Grps_ad16" > 5 ;

-- EJERCICIO 2. OBTENER AQUELLAS CUÑAS DE RADIO EMITIDAS POR CADENA SER O 40 PRINCIPALES. ¿CUANTAS SON?
SELECT *
FROM "Marketing"."Radio"
WHERE  "Radio"."Formato" = 'CUÑA' AND "Radio"."Emisora" IN ('CADENA SER', '40 PRINCIPALES') ;

-- EJERCICIO 3. OBTENER LOS REGISTROS DE SOCIAL CUYO NUMERO DE IMPRESIONES SEA SUPERIOR A 100  
--              Y LA CAMPAÑA TENGA RELACION CON ENGAGEMENT
SELECT *
FROM "Marketing"."Social"
WHERE "Social"."Impresiones" > 100 AND "Social"."Campaña" LIKE '%Engagement%' 
ORDER BY "Social"."Impresiones" DESC;